version: '1.0'
services:
  code-server:
    container_name: gogs
    hostname: gogs
    image: gogs/gogs
    restart: always
    ports:
      - "22:22"
      - "3000:3000"
    volumes:
      - /www/data/gogs:/data
